version: '2.1'

services:
  vip-service-node:
    image: vip-service-node:latest
    build: .
    environment:
      VIP_CONN_STRING: mongodb://mongo:27017/vipDB
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.9
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db